project_name: easyagent
builds:
  - id: easyagent_server
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./
    flags:
    env:
      - GO111MODULE=on
    ldflags:
    binary: easyagent_server

  - id: easyagent_agent
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./agent/
    flags:
    env:
      - GO111MODULE=on
    ldflags:
    binary: easyagent_agent

archives:
  - id: easyagent
    builds: ["easyagent_server", "easyagent_agent"]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - configs/server.yaml
      - configs/agent.yaml

