Agent:
  WsAddr: ws://127.0.0.1:8888/websocket
  Token:
  TmpPath: ./_temp/tmp/
  ScriptPath: ./_temp/scripts/
  ExecLogPath: ./_temp/runlogs/
  Desc:
  ExecTimeout: 30000
  Charset: GB18030
Log:
  LogFilepath: ./_temp/logs/
  LogFilename: agent.log
  LogMaxSize: 600
  LogMaxAge: 10