Agent:
  WsAddr: ws://127.0.0.1:8080/websocket
  Token: 111111
  TmpPath: tmp/
  ScriptPath: scripts/
  ExecLogPath: runlogs/
  Desc:
  ExecTimeout: 30000
  Charset: GB18030
Log:
  LogFilepath: logs/
  LogFilename: agent.log
  LogMaxSize: 600
  LogMaxAge: 10