Server:
  RunMode: debug
  HttpPort: 8888
  Timeout: 300000000000
  ReadTimeout: 300000000000
  WriteTimeout: 300000000000
  DefaultPageSize: 10000
  MaxPageSize: 10000
Log:
  LogFilepath: ./_temp/logs/
  LogFilename: server.log
  LogMaxSize: 600
  LogMaxAge: 10