Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 10
  WriteTimeout: 10000
  DefaultPageSize: 10000
  MaxPageSize: 100
Log:
  LogFilepath: logs/
  LogFilename: server.log
  LogMaxSize: 600
  LogMaxAge: 10