Server:
  RunMode: release
  HttpPort: 8080
  Timeout: 300000000000
  ReadTimeout: 300000000000
  WriteTimeout: 300000000000
  DefaultPageSize: 10000
  MaxPageSize: 10000
Log:
  LogFilepath: logs/
  LogFilename: server.log
  LogMaxSize: 600
  LogMaxAge: 10