definitions:
  errcode.Error:
    type: object
  model.SessionInfo:
    type: object
info:
  contact: {}
  description: easyagent控制管理平台
  termsOfService: https://github.com/mufanh/easyagent
  title: easyagent
  version: "1.0"
paths:
  /api/sessions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.SessionInfo'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取agent连接列表
  /api/sessions/{id}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 关闭agent连接
swagger: "2.0"
